import Head from 'next/head'
import Image from 'next/image'
import Navbar from '../components/Navbar'
import ThemeSwitch from '../components/ThemeSwitch'
import styles from '../styles/Home.module.css'

export async function getStaticProps() {
  const res = await fetch(`https://api-dhillon.deta.dev/`)
  const data = await res.json()

  if (!data) {
    return {
      notFound: true,
    }
  }

  return {
    props: { data }, // will be passed to the page component as props
  }
}

export default function Home({ data }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Navbar />
        {data.map((ap, index) => {
          return (
            <div className={styles.card} key={index}>
              <p className={styles.title}>{ap.title}</p>
              <p className={styles.title}>{ap.singer}</p>
              <p className={styles.description}>{ap.lyricist}</p>
              <p className={styles.description}>{ap.video_link}</p>
            </div>
          )
        })}
      </main >

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div >
  )
}
